Repository itsabdessalam/taskee, pull requests merged in 2020-11, with the labels that each got.

#5 Build/eslint prettier setup
  .eslintrc.js
  .prettierrc.js
  package.json
  src/components/CreateNoteForm.jsx
  src/components/Icon.jsx
  src/components/LoginForm.jsx
  src/components/Option.jsx
  src/components/RegisterForm.jsx
  src/components/Select.jsx
  src/context/Locale.js
  src/context/Theme.js
  src/hooks/useLocalStorage.jsx
  src/layouts/Layout.jsx
  src/pages/createNote.jsx
  src/pages/home.jsx
  src/service-worker.js
  src/serviceWorkerRegistration.js
  src/services/NoteService.js
  src/utils/auth.js
  src/utils/time.js
  yarn.lock
Labels: needs review

#9 feat: add push notification
  public/index.html
  src/pages/home.jsx
  src/service-worker.js
  src/services/NotificationService.js
Labels: feature

#14 feat: subscribe to the notifications of the logged in user
  package.json
  src/layouts/App.jsx
  yarn.lock
Labels: LGTM, feature

#16 feat: add dashboard components v1
  package.json
  src/assets/fonts/circular/CircularStdBlack.woff2
  src/assets/fonts/circular/CircularStdBold.woff2
  src/assets/fonts/circular/CircularStdBook.woff2
  src/assets/fonts/circular/CircularStdMedium.woff2
  src/assets/fonts/circular/style.css
  src/assets/fonts/euclid-flex/EuclidFlexBold.woff2
  src/assets/fonts/euclid-flex/EuclidFlexMedium.woff2
  src/assets/fonts/euclid-flex/EuclidFlexRegular.woff2
  src/assets/fonts/euclid-flex/EuclidFlexSemibold.woff2
  src/assets/fonts/euclid-flex/style.css
  src/assets/fonts/main.css
  src/assets/images/taskee-logo.png
  src/assets/images/taskee_full_black.png
  src/assets/images/taskee_icon.png
  src/components/Button.jsx
  src/components/Checklist.jsx
  src/components/CreateNoteForm.jsx
  src/components/DatePicker.jsx
  src/components/Deadline.jsx
  src/components/Editor.jsx
  src/components/Icon.jsx
  src/components/Input.jsx
  src/components/LocaleSelector.jsx
  src/components/LoginForm.jsx
  src/components/Note.jsx
  src/components/NoteCard.jsx
  src/components/NotesList.jsx
  src/components/RegisterForm.jsx
  src/components/Reminders.jsx
  src/components/Select.jsx
  src/components/TabItem.jsx
  src/components/Tabs.jsx
  src/components/Task.jsx
  src/components/TaskModal.jsx
  src/components/TemplateSelector.jsx
  src/components/ThemeSwitcher.jsx
  src/components/Title.jsx
  src/components/index.js
  src/config/locales.js
  src/config/theme.js
  src/context/App.js
  src/context/Locale.js
  src/context/Theme.js
  src/layouts/App.jsx
  src/layouts/Container.jsx
  src/layouts/Footer.jsx
  src/layouts/Layout.jsx
  src/layouts/Navigation.jsx
  src/layouts/index.js
  src/pages/home.jsx
  src/pages/notes.jsx
  src/translations/en.js
  src/translations/fr.js
  src/utils/date.js
  src/utils/language.js
  src/utils/time.js
  yarn.lock
Labels: feature, needs review
